# Generated by Django 3.1.7 on 2021-03-12 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 23, 43, 41, 945272)),
        ),
    ]
